#!/bin/bash
set -Eeuo pipefail
if [[ "${#}" -ne 1 ]]; then
	echo "Usage: bash ${0} SHELL_SCRIPT_PATH ..." >&2
	exit 1
fi
base_path="$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
shell_script_path="${1}" && shift
if [[ ! -f "${shell_script_path}" ]]; then
	echo "File ${shell_script_path} not found" >&2
	exit 1
fi
run_bash_bat_path="$(realpath -- "${base_path}/run-bash.bat")"
if [[ ! -f "${run_bash_bat_path}" ]]; then
	echo "File ${run_bash_bat_path} not found" >&2
	exit 1
fi
wrapper_bat_file_path="${shell_script_path}.bat"
echo "Generating ${wrapper_bat_file_path}"
shell_script_file_name="$(basename -- "${shell_script_path}")"
run_bash_relative_path="$(realpath --relative-to "$(dirname -- "${shell_script_path}")" -- "${run_bash_bat_path}")"
wrapper_bat_file_content="$(
	cat <<EOF
@echo off
call "%~dp0${run_bash_relative_path}" "%~dp0${shell_script_file_name}" %* || if /i %0 == "%~0" pause
exit /b %ERRORLEVEL%
EOF
)"
echo "${wrapper_bat_file_content}" >"${wrapper_bat_file_path}"
