#!/bin/bash
set -Eeuo pipefail
cd "$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
cd ..
excluded_diagnostics=(
	CA1823 # deletes code
	IDE0010 # adds code
	IDE0051 # deletes code
	IDE0052 # deletes code
	IDE0059 # deletes code
	IDE0060 # deletes code
	IDE0130 # crashes
	IDE1006 # not implemented
	SYSLIB1045 # adds code
)
set -x
dotnet format --verbosity normal --severity info --exclude-diagnostics "${excluded_diagnostics[@]}" "${@}"
