#!/bin/bash
set -Eeuo pipefail
cd "$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
while IFS= read -r -d '' file_path; do
	echo "Fixing permissions for ${file_path}"
	chmod +x "${file_path}"
	git add --chmod=+x "${file_path}" || true
done < <(find . -type f -not -name '*.*' -print0)
while IFS= read -r -d '' bat_file_path; do
	file_path="${bat_file_path%.*}"
	if [[ ! -f "${file_path}" ]]; then
		echo "Deleting unused ${bat_file_path}"
		rm -- "${bat_file_path}"
	fi
done < <(find . -type f -iname '?*.bat' -not -iregex '.*/_internal/.*' -print0)
while IFS= read -r -d '' file_path; do
	./_internal/generate-wrapper-bat-file "${file_path}"
done < <(find . -type f -not -name '*.*' -not -iregex '.*/_internal/.*' -print0)
